// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/22/2025, 4:50:33 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/root/dev/koishi-meme/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/dev/koishi-meme/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/dev/koishi-meme/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/dev/koishi-meme/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/dev/koishi-meme/plugins/**/*.{js,ts,mjs}","/root/dev/koishi-meme/composables/**/*.{js,ts,mjs}","/root/dev/koishi-meme/utils/**/*.{js,ts,mjs}","/root/dev/koishi-meme/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/root/dev/koishi-meme/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/root/dev/koishi-meme/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;