// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/8/2024, 1:32:21 PM
const configMerger = require("/home/dev/koishi-meme/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/dev/koishi-meme/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/plugins/**/*.{js,ts,mjs}","/home/dev/koishi-meme/composables/**/*.{js,ts,mjs}","/home/dev/koishi-meme/utils/**/*.{js,ts,mjs}","/home/dev/koishi-meme/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/dev/koishi-meme/app.config.{js,ts,mjs}"] }));

module.exports = config
